### ISSUE TITLE
set_prior is sensitive to the input order 

### ISSUE THREAD

**Issue by hyunjimoon** [Data4DM/stanify#32]
@Dashadower, regarding adding one layer for hierarchical model by passing "_loc" parameter as string current implementation is sensitive to the order of input. Do you have any go idea to fix this?

When the input order is
```
    ("adj_frac1_loc", "normal", .25, .25* .1, 0), # order
    ("adj_frac1", "normal", "adj_frac1_loc", .25 *.1, 0),
    ("adj_frac2", "normal", .125,.125 *.1, 0),
```
it works well, but when adj_frac1_loc appears before its prior (the third line), 

```
    ("adj_frac1", "normal", "adj_frac1_loc", .25 *.1, 0),
    ("adj_frac2", "normal", .125,.125 *.1, 0),
    ("adj_frac1_loc", "normal", .25, .25* .1, 0), 
```
returns the following error:
```
/Users/hyunjimoon/Dropbox/stanify/venv/bin/python /Users/hyunjimoon/Dropbox/stanify/vignette/test.py 
Traceback (most recent call last):
  File "/Users/hyunjimoon/Dropbox/stanify/vignette/test.py", line 71, in <module>
    idata_orig, model = draws2data2draws('../vensim_models/inventory/hier2_stock.mdl', setting, precision, numeric, prior, output_format)
  File "/Users/hyunjimoon/Dropbox/stanify/stanify/calibrator/draws_data_mapper.py", line 72, in draws2data2draws
    model = transform_input(vensim, setting, precision, numeric, prior, idata_kwargs)
  File "/Users/hyunjimoon/Dropbox/stanify/stanify/calibrator/draws_data_mapper.py", line 206, in transform_input
    model.set_prior(est_param[0], est_param[1], est_param[2], est_param[3], lower = est_param[4])
  File "/Users/hyunjimoon/Dropbox/stanify/stanify/builders/stan_model.py", line 180, in set_prior
    raise Exception(f"{sample_string} : '{name}' doesn't exist in the Vensim model or the Stan model!")
Exception: adj_frac1 ~ normal(adj_frac1_loc, 0.025) : 'adj_frac1_loc' doesn't exist in the Vensim model or the Stan model!
```

**Comment by hyunjimoon** [comment]
The results seem stochastic as the first line sometimes doesn't work.

**Comment by hyunjimoon** [comment]
We should make the input as list as set doesn't preserve order.

```
prior = {
    ("inventory_adjustment_time", "normal", 8.0, 0.8, 0),
    ("wip_adjustment_time", "normal", 2, 0.02, 0),
    ("m_noise_scale", "normal", init_order * .1, init_order * .01, 0)
}

```
