### ISSUE TITLE
Permission denied with two .nc files

### ISSUE THREAD

**Issue by hyunjimoon** [Data4DM/stanify#9]
```
Traceback (most recent call last):
  File "/Users/hyunjimoon/Dropbox/15879-Fall2022/Homeworks/HW7/stanify/demo_draws2data2draws.py", line 31, in <module>
    draws2data2draws('vensim_models/mng_pop/mng_pop.mdl', setting, numeric, prior, S, M, N)
  File "/Users/hyunjimoon/Dropbox/15879-Fall2022/Homeworks/HW7/stanify/stanify/calibrator/draws_data_mapper.py", line 83, in draws2data2draws
    posterior_s = data2draws(model, numeric, chains=4, iter_sampling=int(M/4))
  File "/Users/hyunjimoon/Dropbox/15879-Fall2022/Homeworks/HW7/stanify/stanify/calibrator/draws_data_mapper.py", line 37, in data2draws
    post_ppc.draws_xr().to_netcdf(f"{data_path}/estimator.nc")
  File "/opt/homebrew/lib/python3.10/site-packages/xarray/core/dataset.py", line 1882, in to_netcdf
    return to_netcdf(  # type: ignore  # mypy cannot resolve the overloads:(
  File "/opt/homebrew/lib/python3.10/site-packages/xarray/backends/api.py", line 1193, in to_netcdf
    store = store_open(target, mode, format, group, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 384, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/opt/homebrew/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 332, in __init__
    self.format = self.ds.data_model
  File "/opt/homebrew/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 393, in ds
    return self._acquire()
  File "/opt/homebrew/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 387, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/homebrew/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 189, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/opt/homebrew/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 207, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'/Users/hyunjimoon/Dropbox/15879-Fall2022/Homeworks/HW7/stanify/data/draws2data2draws_mngpop_multiS2/estimator.nc'
```

**Comment by hyunjimoon** [comment]
It opens well in write binary:
>  a = open("stanify/data/draws2data2draws_mngpop_multiS2/estimator.nc", "wb")

**Comment by hyunjimoon** [comment]
first delete then write
